apiVersion: apps/v1
kind: Deployment #define the type of object that I want to create
metadata:
  name: second-app-deployment
spec: #specification of the deployment
  replicas: 3   #create 3 Pod
  selector: #the selector is mandatory - indicates what Pods are controlled/belongs by this deployment
    matchLabels:
      app: second-app
      tier: backend

  template:   #define the Pod that we will create
    metadata: #metadate of the pod
      labels:
        app: second-app
        tier: backend
    spec: # specification of the Pod
      containers:
        - name: second-node # - defines a list
          image: vitorgilsilva/kub-first-app:2
        # - name: ...
        #   image: ...
